### ISSUE TITLE
PULSE_COOKIE_DATA is empty for non-English locales, but Chromium connects to PulseAudio anyway (without disabled authentication)

### ISSUE THREAD

**Issue by wrzomar** [HenningThiemann/docker-chromium-armhf#12]
I've to add LC_ALL=C before pax11publish, so the grep part of this command would have its cookie, instead of ciasteczko ;-)
But Chromium somehow connects (or not) regardless of the contents of this variable. It didn't connect to pulseaudio when it was stopped, then started in a terminal (pulseaudio -k; pulseaudio --daemonize=no -v) or stopped and restarted using systemd service. To get useful logs I had to change pulseaudio.service and add -v parameter, then reboot (or should I say power off and on, because my display don't work after reboot and logging out just causes session to crash, so e.g. adding my user to some group requires powering off and on, but it's not important here, it's just annoying).
Why this PulseAudio authentication isn't working the way it suppose to? What am I missing?

**Comment by wrzomar** [comment]
I've made a few tests using audacious as pulse client (because it is one of a few music players that can actually use remote pulse servers). Audacious will connect to whatever pulse server the PULSE_SERVER points to, but it will connect without PULSE_COOKIE only if remote pulse server doesn't require authentication. If pulse server require authentication, audacious needs PULSE_COOKIE with the absolute path to the cookie file with the same contents, as the server's cookie. But when audacious uses remote X server (using DISPLAY variable), then it will get the pulse cookie from that X server's properties, if cookie matches the one pulse server uses, audacious will connect. There is also the pulse cookie inside container /home/mediaguy/.config/pulse/cookie but it is probably used when Chromium can't connect to a remote pulse server (and uses pulse server from container, I think).
Chromium doesn't need PULSE_COOKIE_DATA or 'Don't require authentication' option set on the host pulse server. 'Don't require authentication' without firewall is quite dangerous, but firewall will also block docker container from connecting to the host's pulse server, it will require allowing TCP connections to 4713 port from the docker subnet.

**Comment by wrzomar** [comment]
Also the PULSE_COOKIE variable is weird, but it works like in 
[https://wiki.archlinux.org/index.php/PulseAudio/Configuration#Connection_&_authentication](url)
When you try to send just audio to a remote host, it accepts path to the cookie file, but when you e.g. using SSH X forwarding it's accepting hex string with cookie or path to cookie (or is not needed - client gets it from X11). The More You Know 🌠
I can't find anything about the PULSE_COOKIE_DATA variable, but it is only mentioned with docker.

**Comment by wrzomar** [comment]
Now I'm testing chromium-armhf with PULSE_COOKIE instead of PULSE_COOKIE_DATA and `xxd -c 256 -p $HOME/.config/pulse/cookie` instead of `LC_ALL=C pax11publish -d | grep --color=never -Po '(?<=^Cookie: ).*'` because the outcome is the same and the latter reads values from X root window that were published by pulseaudio (if I understand it correctly).

**Comment by Boteium** [comment]
I not sure about PULSE_COOKIE or PULSE_COOKIE_DATA variable. As for the xxd vs pax11publish, there might be some cases xxd is better.

In some scenarios, if pulseaudio is manually started rather than started by a session manager, module-x11-publish might not be loaded and thus causing pax11publish to give empty output. In this case, using xxd instead of pax11publish might have an advantage.

Starting pulseaudio by start-pulseaudio-x11 rather than pulseaudio --start will load the module-x11-publish and avoid this problem.

**Comment by wrzomar** [comment]
I've decided to set PULSE_COOKIE this complicated way:
```
PULSE_COOKIE=`COOKIE_FILE="$HOME/.config/pulse/cookie"; COOKIE_FROM_FILE=$(test -f "${COOKIE_FILE}" && xxd -c 256 -p "${COOKIE_FILE}"); test "$(LC_ALL=C pax11publish -d | grep --color=never -Po '(?<=^Cookie: ).*')" != "${COOKIE_FROM_FILE}" && echo ${COOKIE_FROM_FILE}`
```

**Comment by HenningThiemann** [comment]
I've merged the pr. Feel free to re-open if this is not solved by now.
