### ISSUE TITLE
GUI enable remote connections

### ISSUE THREAD

**Issue by aubreybailey** [HenningThiemann/docker-chromium-armhf#15]
paprefs (which is used in most popular distributions) has remote connections and anonymous login disabled by default.
I think it would be helpful to add a similar image and checkbox to your guide.

https://mauriziosiagri.files.wordpress.com/2012/07/pasted_image001.png

P.S. Thanks for the great work!

**Comment by wrzomar** [comment]
I've checked that only 'Enable network access to local sound devices' is actually required. There is also a pull request #13 which checks if native-protocol-tcp is enabled and enables it if needed. For me, the only thing that was blocking connections with pulseaudio was firewall blocking also all network connections from docker container. I've also discovered that in my case the 'PULSE_COOKIE_DATA' variable was empty and it didn't stop Chromium to connect to my pulseaudio server. But if you have enabled all the options from this PNG file (and you are not using a firewall), your pulseaudio can be easily accessible (and discoverable) from other machines in the network you're connected to, e.g. the public WiFi. You can use e.g. audacious player to play music on your machine from some other machine in your LAN (rhythmbox crashed last time I've checked it). But I didn't check the microphone remotely, yet (but it's a good idea to do). But if you are using Pinebook Pro, it has hardware switch for microphone anyway :)
But there should be some info in the readme file about enabling network access.

**Comment by HenningThiemann** [comment]
I've merged the pr. Feel free to re-open if this is not solved by now.
