### ISSUE TITLE
docker build fails due to unsigned package repo

### ISSUE THREAD

**Issue by sgbeal** [HenningThiemann/docker-chromium-armhf#6]
Running the docker build, per the readme, aborts with:

```
Reading package lists...
W: GPG error: http://deb.debian.org/debian unstable InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian unstable InRelease' is not signed.
```

**Comment by sgbeal** [comment]
i've tried several options suggested around the web, up to and including replacing the sources.list to the dockerfile:

```
RUN echo "deb [trusted=yes] http://deb.debian.org/debian unstable InRelease" > /etc/apt/sources.list
```

but such options led to a new error:

```
W: GPG error: http://deb.debian.org/debian unstable InRelease: At least one invalid signature was encountered.
E: Release file for http://deb.debian.org/debian/dists/unstable/InRelease is not valid yet (invalid for another 18519d 2h 11min 41s). Updates for this repository will not be applied.
```

**Comment by sgbeal** [comment]
(Didn't mean to close this - mean to discard my useless comment instead.)

**Comment by HenningThiemann** [comment]
Hi @sgbeal,

unfortunately, I can not reproduce your error. I've just built this via GitHub Actions, and there are no errors in my case. 

Could you try to build it again with the flag --no-cache ?

**Comment by sgbeal** [comment]
Thank you for checking. `--no-cache` makes no difference here. Here's the full output, noting that steps 4 and 5 of the docker output show changes i made to the dockerfile to try to bypass the key check:

```
[pi@pi4b8:~/src/docker-chromium-armhf]$ docker build -t hthiemann/chromium-armhf . --no-cache
Sending build context to Docker daemon  160.5MB
Step 1/16 : FROM docker.io/arm32v7/debian:unstable
unstable: Pulling from arm32v7/debian
97bc44265606: Pull complete 
Digest: sha256:7279e7f8bd64a3dfd1133ea57aa85731a7f8d25e2a57f98d652dc0464b81043b
Status: Downloaded newer image for arm32v7/debian:unstable
 ---> a66a9ed0e59e
Step 2/16 : MAINTAINER Henning Thiemann <henning.thiemann@gmail.com>
 ---> Running in b12cd72aa066
Removing intermediate container b12cd72aa066
 ---> ebe0e8358520
Step 3/16 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in bb8963a1de37
Removing intermediate container bb8963a1de37
 ---> ce4f5053d3a4
Step 4/16 : RUN echo "deb [trusted=yes] http://deb.debian.org/debian unstable InRelease" > /etc/apt/sources.list
 ---> Running in ca66d7df52e7
Removing intermediate container ca66d7df52e7
 ---> c3ac41e4d76c
Step 5/16 : RUN apt-get update --allow-insecure-repositories   && apt-get install -y --no-install-recommends   git fontconfig <SNIP> libgl1-mesa-dri
 ---> Running in 91bdecdeabfc
Get:1 http://deb.debian.org/debian unstable InRelease [146 kB]
Ign:1 http://deb.debian.org/debian unstable InRelease
Reading package lists...
W: GPG error: http://deb.debian.org/debian unstable InRelease: At least one invalid signature was encountered.
E: Release file for http://deb.debian.org/debian/dists/unstable/InRelease is not valid yet (invalid for another 18520d 2h 25min 29s). Updates for this repository will not be applied.
The command '/bin/sh -c apt-get update --allow-insecure-repositories   && apt-get install -y --no-install-recommends   git <SNIP> libgl1-mesa-dri' returned a non-zero code: 100
```

This is an up-to-date installation of 32-bit Raspbian on a Pi 4B (64-bit - still waiting on a stable 64-bit OS build from the RPi folks):

```
$ cat /etc/issue; uname -a
Raspbian GNU/Linux 10 \n \l

Linux pi4b8 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
```

**Comment by HenningThiemann** [comment]
Pretty sure you should be able to install widevine etc. directly if you are on armhf (32-bit ARM) userland. No need to use the docker container in this case. This is just a hack to make it work on aarch64 userland

Alternatively, you could try to pull the docker image from my docker hub repository directly, so you do not have to build it on your own: `docker pull hthiemann/docker-chromium-armhf`

**Comment by sgbeal** [comment]
> Pretty sure you should be able to install widevine etc. directly if you are on armhf (32-bit ARM) userland.
> No need to use the docker container in this case. This is just a hack to make it work on aarch64 userland

i actually have it installed *outside* of docker but i'd prefer to have that particular app in docker (no idea why, though - it's just something i'm itching to try).

> Alternatively, you could try to pull the docker image from my docker hub repository directly, so you do not have to build it on your own: docker pull hthiemann/docker-chromium-armhf

That's pulling now - i'm no docker expert, so i'll need to poke at it to figure out how to use it, but it sounds like a good start. Thank you!

i'm going to go ahead and close this, as it appears to be a peculiarity of my environment. (i wonder if my Pi Hole server (a DNS server which blocks ads for the whole home network) is blocking something which is needed there... Hmm.)

**Comment by sgbeal** [comment]
Follow-up: i'm not 100% sure i'm doing this correctly, but...

```
docker image tag hthiemann/docker-chromium-armhf chromium
docker container run chromium
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
```

It says the same thing when run as root. Oh, well. No big deal.

Happy Hacking!

**Comment by sgbeal** [comment]
Edit: doh, facepalm. The readme gives a whole slew of args for the `container run` call (As mentioned before, i'm not a Docker Guy), but i've already deleted it all so won't try it out again just now.
