### ISSUE TITLE
Please change the IP address Chromium uses to connect to the PulseAudio server

### ISSUE THREAD

**Issue by wrzomar** [HenningThiemann/docker-chromium-armhf#9]
Now the IP address is set by this line:
`addrip="$(hostname -i | grep -v '127.0.0.1' | awk '{ print $1}')"`
which would set it to the IP of a physical interface, if interface goes down or IP changes, user have to restart chromium-armhf script. Instead you can set this variable to the IP address of the docker interface:
`addrip="$(docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}')"`
Chromium will be connected to the PulseAudio server continuously, even during connecting to another WiFi network.
I've tested it on my PBP by changing WiFi networks, using internal wlan and USB wlan dongle, etc. It works. PulseAudio listens on all interfaces, docker doesn't like 127.0.0.1 for some reason, but you don't have to use a physical interface for this purpose.

**Comment by HenningThiemann** [comment]
should be closed via 2217261

Feel free to reopen if this is not the case
